services:
  # Node.js Polly Server instances
  ps1:
    build:
      context: .
      dockerfile: Dockerfile # Path to your Dockerfile
    hostname: ps1
    networks:
      - polly-network

  ps2:
    build:
      context: .
      dockerfile: Dockerfile # Path to your Dockerfile
    hostname: ps2
    networks:
      - polly-network

  ps3:
    build:
      context: .
      dockerfile: Dockerfile # Path to your Dockerfile
    hostname: ps3
    networks:
      - polly-network

  # NGINX load balancer
  nginx:
    image: nginx:latest # Use the official NGINX image
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Mount your NGINX configuration file
    ports:
      - "8080:8080" # Expose NGINX on port 8080
    networks:
      - polly-network

networks:
  polly-network:
    driver: bridge
