services:
  # NGINX Layer 7 Proxy
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./ws.conf:/etc/nginx/nginx.conf:ro # Mount NGINX config as read-only
    ports:
      - "80:80" # Expose NGINX on host port 80
    depends_on:
      - wsserver1
      - wsserver2
      - wsserver3
      - wsserver4
    networks:
      - app-network

  # WebSocket Server 1
  wsserver1:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - PORT=2222
    networks:
      - app-network

  # WebSocket Server 2
  wsserver2:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - PORT=3333
    networks:
      - app-network

  # WebSocket Server 3
  wsserver3:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - PORT=4444
    networks:
      - app-network

  # WebSocket Server 4
  wsserver4:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - PORT=5555
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
